//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_Diplom_2_Pisarev_Aleksei
{
    using System;
    using System.Collections.Generic;
    
    public partial class Haracteristiki
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Haracteristiki()
        {
            this.Haracteristiki_Complect = new HashSet<Haracteristiki_Complect>();
        }
    
        public int Id_Haracteristiki { get; set; }
        public string Nazvanie { get; set; }
        public int Id_tipa_complect { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Haracteristiki_Complect> Haracteristiki_Complect { get; set; }
        public virtual Tipi_complect Tipi_complect { get; set; }
    }
}
