//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_Diplom_2_Pisarev_Aleksei
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hatacteristiki_PO
    {
        public int Id_harakt_PO { get; set; }
        public int Id_tipa_PO { get; set; }
        public int Id_PO { get; set; }
        public System.DateTime Data_ustanovki { get; set; }
        public System.DateTime Data_posled_obnovl { get; set; }
        public int Id_oborud { get; set; }
    
        public virtual PO PO { get; set; }
        public virtual Tipi_oborud Tipi_oborud { get; set; }
        public virtual Tipi_PO Tipi_PO { get; set; }
    }
}
