//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_Diplom_2_Pisarev_Aleksei
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oborudovanie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Oborudovanie()
        {
            this.Complect_oborud = new HashSet<Complect_oborud>();
        }
    
        public int Id_oborud { get; set; }
        public int Id_tipa_oborud { get; set; }
        public int Id_Sotrud { get; set; }
        public int Id_otdela { get; set; }
        public string imya_oborud { get; set; }
        public string Ip_adres { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Complect_oborud> Complect_oborud { get; set; }
        public virtual Otdeli Otdeli { get; set; }
        public virtual Sotrudniki Sotrudniki { get; set; }
        public virtual Tipi_oborud Tipi_oborud { get; set; }
    }
}
