//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_Diplom_2_Pisarev_Aleksei
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odsujd_zayavki
    {
        public int Id_obsujd { get; set; }
        public int Id_zayavki { get; set; }
        public System.DateTime Data_vramya { get; set; }
        public string Kommentarij { get; set; }
        public int Id_kem_soversh { get; set; }
        public int Id_komu { get; set; }
    
        public virtual Sotrudniki Sotrudniki { get; set; }
        public virtual Sotrudniki Sotrudniki1 { get; set; }
        public virtual Zayavki Zayavki { get; set; }
    }
}
