//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_Diplom_2_Pisarev_Aleksei
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sklade
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sklade()
        {
            this.Complect_oborud = new HashSet<Complect_oborud>();
        }
    
        public int Id_Sklad { get; set; }
        public int Id_tipa_complect { get; set; }
        public int Id_firmi { get; set; }
        public string model { get; set; }
        public int Vsego { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Complect_oborud> Complect_oborud { get; set; }
        public virtual Firmi Firmi { get; set; }
        public virtual Tipi_complect Tipi_complect { get; set; }
    }
}
