//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_Diplom_2_Pisarev_Aleksei
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sotrudniki
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sotrudniki()
        {
            this.Oborudovanie = new HashSet<Oborudovanie>();
            this.Odsujd_zayavki = new HashSet<Odsujd_zayavki>();
            this.Odsujd_zayavki1 = new HashSet<Odsujd_zayavki>();
            this.Zayavki = new HashSet<Zayavki>();
        }
    
        public int Id_sotrud { get; set; }
        public string FIO { get; set; }
        public int Id_otdela { get; set; }
        public int Id_doljnosti { get; set; }
        public System.DateTime DR { get; set; }
        public string Adres { get; set; }
        public string Telefon { get; set; }
        public string e_mail { get; set; }
        public string Kommentatij { get; set; }
        public int role { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual Doljnosti Doljnosti { get; set; }
        public virtual Doljnosti Doljnosti1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oborudovanie> Oborudovanie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Odsujd_zayavki> Odsujd_zayavki { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Odsujd_zayavki> Odsujd_zayavki1 { get; set; }
        public virtual Otdeli Otdeli { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zayavki> Zayavki { get; set; }
    }
}
