//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_Diplom_2_Pisarev_Aleksei
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zayavki
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zayavki()
        {
            this.Odsujd_zayavki = new HashSet<Odsujd_zayavki>();
        }
    
        public int Id_zayavki { get; set; }
        public int Id_sotrud { get; set; }
        public int Id_otdela { get; set; }
        public System.DateTime Data { get; set; }
        public System.DateTime Data_zaversh { get; set; }
        public int Id_sotrud_teh { get; set; }
        public int Id_temi_zayavki { get; set; }
        public string Vajnost { get; set; }
        public string Statys { get; set; }
        public string Sostoyanie { get; set; }
        public Nullable<int> Id_tipa_PO { get; set; }
        public int Id_PO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Odsujd_zayavki> Odsujd_zayavki { get; set; }
        public virtual Otdeli Otdeli { get; set; }
        public virtual PO PO { get; set; }
        public virtual Sotrudniki Sotrudniki { get; set; }
        public virtual Temi_zayavok Temi_zayavok { get; set; }
        public virtual Tipi_PO Tipi_PO { get; set; }
    }
}
